# Generated by Django 4.2 on 2024-08-14 13:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery', '0003_remove_location_parent_area_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliveryprice',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='delivery.area'),
        ),
        migrations.AlterField(
            model_name='deliveryprice',
            name='weight_from',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='deliveryprice',
            name='weight_to',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
