# Generated by Django 5.0.6 on 2024-07-14 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_alter_brandcategory_slug_alter_category_slug_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'ordering': ('-title',), 'verbose_name_plural': 'BrandCategories'},
        ),
    ]
