# Generated by Django 5.0.6 on 2024-07-14 01:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_alter_brandcategory_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brandcategory',
            options={'ordering': ('title',), 'verbose_name_plural': 'BrandCategories'},
        ),
    ]
