# Generated by Django 5.0.6 on 2024-07-14 02:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_remove_brandcategory_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='ordering',
            field=models.IntegerField(default=0),
        ),
    ]
