# Generated by Django 5.0.6 on 2024-07-21 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_brandcategory_ordering'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandcategory',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploads/'),
        ),
    ]
