# Generated by Django 4.2 on 2024-08-02 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0002_order_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='transaction_ref',
            field=models.CharField(blank=True, editable=False, max_length=225, null=True),
        ),
    ]
