# Generated by Django 4.2 on 2024-08-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0003_alter_order_transaction_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_amount',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
