# Generated by Django 4.2 on 2024-08-12 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('coupon', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='coupon',
            name='num_used',
            field=models.IntegerField(default=0),
        ),
    ]
